name: Node.js CI Windows Platform

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x, 19.x ]
        architecture: [x64, x86]
        os:
          - windows-2019
          - windows-2022
        exclude:
          - node-version: 14.x
            os: windows-2022 # Node.JS 14.x GYP does not support Visual Studio 2022
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
    - name: Check Node.js installation
      run: |
        node --version
        npm --version
    - name: Install dependencies
      run: |
        npm install
    - name: npm test
      run: |
        npm run pretest -- --verbose
        node test
